package agh.msc.xbowbase.jna;


/**
 * Contains Xbow statuses returned by helper methods.
 *
 * @author cieplik
 */
public enum XbowStatus {

	XBOW_STATUS_OK,
	XBOW_STATUS_PROP_PARSE_ERR,
	XBOW_STATUS_NOTFOUND,
	XBOW_STATUS_FLOW_INCOMPATIBLE,
	XBOW_STATUS_UNKNOWN_ERR,
        XBOW_STATUS_TOO_LONG_NAME,
	XBOW_STATUS_INVALID_NAME,
	XBOW_STATUS_OPERATION_FAILURE,
      	XBOW_STATUS_TOO_LONG_PARENT_NAME,
	XBOW_STATUS_INVALID_PARENT_NAME

}
